projectname    GumGraphics

srcdir         src
exampledir     examples

findlibraries  SELF GumEssentials GumCodecs GumPrimitives GROUP(GumGLFW GumDesktop) GumSystem GumMaths
headerfiles    gum-graphics Graphics/
examples       