projectname    GumGraphics

srcdir         src
exampledir     examples

findlibraries  SELF GumCodecs GumPrimitives GumEssentials GumDesktop GumSystem GumMaths
headerfiles    gum-graphics Graphics/
examples       
